from __future__ import annotations

from typing import Protocol
from uuid import UUID

from cloth_vision_api.domain.models import AuthIdentity, User


class IdentityRepository(Protocol):
    def add_user(self, user: User) -> User: ...
    def get_user(self, user_id: UUID) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def add_auth_identity(self, identity: AuthIdentity) -> AuthIdentity: ...
    def get_auth_identity(self, provider: str, subject: str) -> AuthIdentity | None: ...
