from typing import Protocol
from uuid import UUID

from cloth_vision_api.domain.models import Closet, FashionItem


class WardrobeRepository(Protocol):
    def add_closet(self, closet: Closet) -> Closet: ...
    def get_closet(self, closet_id: UUID) -> Closet | None: ...
    def list_closets(self, user_id: UUID) -> list[Closet]: ...
    def add_item(self, item: FashionItem) -> FashionItem: ...
    def get_item(self, item_id: UUID) -> FashionItem | None: ...
    def list_items(self, closet_id: UUID) -> list[FashionItem]: ...
    def save_item(self, item: FashionItem) -> FashionItem: ...
    def delete_item(self, item_id: UUID) -> bool: ...
