from __future__ import annotations

from pathlib import Path
from typing import BinaryIO, Protocol
from uuid import UUID

from cloth_vision_core import AnalysisResult

from cloth_vision_api.domain.models import AuthIdentity, Closet, FashionItem, User


class Repository(Protocol):
    def add_user(self, user: User) -> User: ...
    def get_user(self, user_id: UUID) -> User | None: ...
    def get_user_by_email(self, email: str) -> User | None: ...
    def add_auth_identity(self, identity: AuthIdentity) -> AuthIdentity: ...
    def get_auth_identity(self, provider: str, subject: str) -> AuthIdentity | None: ...
    def add_closet(self, closet: Closet) -> Closet: ...
    def get_closet(self, closet_id: UUID) -> Closet | None: ...
    def list_closets(self, user_id: UUID) -> list[Closet]: ...
    def add_item(self, item: FashionItem) -> FashionItem: ...
    def get_item(self, item_id: UUID) -> FashionItem | None: ...
    def list_items(self, closet_id: UUID) -> list[FashionItem]: ...
    def save_item(self, item: FashionItem) -> FashionItem: ...
    def delete_item(self, item_id: UUID) -> bool: ...


class ImageStorage(Protocol):
    def save(self, item_id: UUID, filename: str, stream: BinaryIO) -> str: ...
    def path_for(self, key: str) -> Path: ...
    def delete(self, key: str) -> None: ...


class ItemAnalyzer(Protocol):
    def analyze(self, image_path: Path) -> AnalysisResult: ...


class PasswordManager(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...


class TokenManager(Protocol):
    def create_access_token(self, user_id: UUID) -> tuple[str, int]: ...
    def decode_user_id(self, token: str) -> UUID: ...
