"""expand wireframe domain schema

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-04 13:47:42.162205
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outfits",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("scheduled_for", sa.Date(), nullable=True),
        sa.Column("occasion", sa.String(length=80), nullable=True),
        sa.Column(
            "weather_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "preference_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("overall_score", sa.Integer(), nullable=True),
        sa.Column(
            "score_breakdown",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "recommendation_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("stylist_tip", sa.Text(), nullable=True),
        sa.Column("scoring_version", sa.String(length=40), nullable=False),
        sa.Column("is_bookmarked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("source IN ('ai', 'user')", name=op.f("ck_outfits_valid_source")),
        sa.CheckConstraint(
            "status IN ('draft', 'recommended', 'accepted', 'archived')",
            name=op.f("ck_outfits_valid_status"),
        ),
        sa.CheckConstraint(
            "overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)",
            name=op.f("ck_outfits_valid_overall_score"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_outfits_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outfits")),
    )
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outfits_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_outfits_user_scheduled", ["user_id", "scheduled_for"], unique=False
        )

    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("device_id", sa.String(length=120), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_tokens.id"],
            name=op.f("fk_refresh_tokens_replaced_by_id_refresh_tokens"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_refresh_tokens_user_id"), ["user_id"], unique=False)

    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("external_subscription_id", sa.String(length=160), nullable=False),
        sa.Column("plan", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('trialing', 'active', 'past_due', 'cancelled', 'expired')",
            name=op.f("ck_subscriptions_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_subscriptions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint(
            "provider", "external_subscription_id", name="uq_subscriptions_provider_external"
        ),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subscriptions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "preferred_styles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "disliked_styles",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "preferred_colors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "fit_preferences",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "ai_settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "notification_settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_preferences")),
    )
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=True),
        sa.Column("profile_image_key", sa.String(length=255), nullable=True),
        sa.Column("location_name", sa.String(length=120), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("gender_identity", sa.String(length=40), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column("body_type", sa.String(length=30), nullable=True),
        sa.Column(
            "personal_colors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "body_type IS NULL OR body_type IN ('straight', 'wave', 'natural')",
            name=op.f("ck_user_profiles_valid_body_type"),
        ),
        sa.CheckConstraint(
            "height_cm IS NULL OR (height_cm >= 80 AND height_cm <= 250)",
            name=op.f("ck_user_profiles_valid_height_cm"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("closet_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source_key", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("detected_item_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source_type IN ('shopping_screenshot', 'ootd')",
            name=op.f("ck_import_jobs_valid_source_type"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_import_jobs_valid_status"),
        ),
        sa.CheckConstraint(
            "detected_item_count >= 0", name=op.f("ck_import_jobs_nonnegative_detected_count")
        ),
        sa.ForeignKeyConstraint(
            ["closet_id"],
            ["closets.id"],
            name=op.f("fk_import_jobs_closet_id_closets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_import_jobs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
    )
    with op.batch_alter_table("import_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_import_jobs_closet_id"), ["closet_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_import_jobs_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_import_jobs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "outfit_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("outfit_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("feedback_type", sa.String(length=20), nullable=False),
        sa.Column(
            "reason_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "feedback_type IN ('like', 'dislike')",
            name=op.f("ck_outfit_feedback_valid_feedback_type"),
        ),
        sa.ForeignKeyConstraint(
            ["outfit_id"],
            ["outfits.id"],
            name=op.f("fk_outfit_feedback_outfit_id_outfits"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_outfit_feedback_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outfit_feedback")),
        sa.UniqueConstraint("user_id", "outfit_id", name="uq_outfit_feedback_user_outfit"),
    )
    with op.batch_alter_table("outfit_feedback", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_outfit_feedback_outfit_id"), ["outfit_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_outfit_feedback_user_id"), ["user_id"], unique=False)

    op.create_table(
        "wear_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("outfit_id", sa.String(length=36), nullable=False),
        sa.Column("worn_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "weather_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("occasion", sa.String(length=80), nullable=True),
        sa.Column("idempotency_key", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["outfit_id"],
            ["outfits.id"],
            name=op.f("fk_wear_events_outfit_id_outfits"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_wear_events_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_wear_events")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_wear_events_user_idempotency"),
    )
    with op.batch_alter_table("wear_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_wear_events_outfit_id"), ["outfit_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_wear_events_user_id"), ["user_id"], unique=False)
        batch_op.create_index("ix_wear_events_user_worn", ["user_id", "worn_at"], unique=False)

    op.create_table(
        "outfit_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("wear_event_id", sa.String(length=36), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column(
            "quick_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "rating >= 1 AND rating <= 5", name=op.f("ck_outfit_reviews_valid_rating")
        ),
        sa.ForeignKeyConstraint(
            ["wear_event_id"],
            ["wear_events.id"],
            name=op.f("fk_outfit_reviews_wear_event_id_wear_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outfit_reviews")),
        sa.UniqueConstraint("wear_event_id", name=op.f("uq_outfit_reviews_wear_event_id")),
    )
    op.create_table(
        "analysis_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=80), nullable=True),
        sa.Column("pipeline_version", sa.String(length=40), nullable=False),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name=op.f("ck_analysis_jobs_valid_status"),
        ),
        sa.CheckConstraint("attempt > 0", name=op.f("ck_analysis_jobs_positive_attempt")),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_analysis_jobs_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
        sa.UniqueConstraint("item_id", "attempt", name="uq_analysis_jobs_item_attempt"),
    )
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_analysis_jobs_item_id"), ["item_id"], unique=False)
        batch_op.create_index(
            "ix_analysis_jobs_status_queued", ["status", "queued_at"], unique=False
        )

    op.create_table(
        "item_images",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("image_type", sa.String(length=30), nullable=False),
        sa.Column("storage_key", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "image_type IN ('original', 'mask', 'transparent', 'normalized', 'thumbnail')",
            name=op.f("ck_item_images_valid_image_type"),
        ),
        sa.CheckConstraint("byte_size > 0", name=op.f("ck_item_images_positive_byte_size")),
        sa.CheckConstraint(
            "width > 0 AND height > 0", name=op.f("ck_item_images_positive_dimensions")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_item_images_item_id_items"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_images")),
        sa.UniqueConstraint("item_id", "image_type", name="uq_item_images_item_type"),
        sa.UniqueConstraint("storage_key", name=op.f("uq_item_images_storage_key")),
    )
    with op.batch_alter_table("item_images", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_item_images_item_id"), ["item_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_item_images_sha256"), ["sha256"], unique=False)

    op.create_table(
        "outfit_items",
        sa.Column("outfit_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IN ('top', 'bottom', 'outer', 'shoes', 'accessory')",
            name=op.f("ck_outfit_items_valid_role"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_outfit_items_nonnegative_position")),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_outfit_items_item_id_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["outfit_id"],
            ["outfits.id"],
            name=op.f("fk_outfit_items_outfit_id_outfits"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("outfit_id", "item_id", name=op.f("pk_outfit_items")),
    )
    op.create_table(
        "item_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_job_id", sa.String(length=36), nullable=False),
        sa.Column("model_name", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("pipeline_version", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("subcategory", sa.String(length=60), nullable=True),
        sa.Column(
            "materials",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "colors",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "style_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "season_tags",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "attributes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column(
            "raw_result",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_item_analyses_valid_confidence"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_item_analyses_analysis_job_id_analysis_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_item_analyses_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_analyses")),
        sa.UniqueConstraint("analysis_job_id", name=op.f("uq_item_analyses_analysis_job_id")),
    )
    with op.batch_alter_table("item_analyses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_item_analyses_item_created", ["item_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_item_analyses_item_id"), ["item_id"], unique=False)

    with op.batch_alter_table("auth_identities", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_auth_identities_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_auth_identities_user_id_users"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_auth_identities_valid_provider"),
            "provider IN ('local', 'apple', 'google', 'kakao')",
        )

    with op.batch_alter_table("closets", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_default", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(
            "uq_closets_default_per_user",
            ["user_id"],
            unique=True,
            postgresql_where=sa.text("is_default"),
            sqlite_where=sa.text("is_default = 1"),
        )
        batch_op.drop_constraint(batch_op.f("fk_closets_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_closets_user_id_users"), "users", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            new_column_name="analysis_status",
            existing_type=sa.String(length=30),
            existing_nullable=False,
        )

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("import_job_id", sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column("brand", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("collection_name", sa.String(length=120), nullable=True))
        batch_op.add_column(
            sa.Column(
                "lifecycle_status",
                sa.String(length=30),
                server_default="active",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("source_type", sa.String(length=30), server_default="manual", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "colors",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "materials",
                sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
                server_default=sa.text("'[]'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("purchase_price", sa.Numeric(precision=12, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("currency", sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column("acquired_at", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("donated_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("last_worn_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(
            sa.Column("wear_count", sa.Integer(), server_default="0", nullable=False)
        )
        batch_op.create_index(
            batch_op.f("ix_items_analysis_status"), ["analysis_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_items_category"), ["category"], unique=False)
        batch_op.create_index(
            "ix_items_closet_category_created",
            ["closet_id", "category", "created_at"],
            unique=False,
        )
        batch_op.create_index("ix_items_closet_created", ["closet_id", "created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_items_import_job_id"), ["import_job_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_items_lifecycle_status"), ["lifecycle_status"], unique=False
        )
        batch_op.drop_constraint(batch_op.f("fk_items_closet_id_closets"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_items_import_job_id_import_jobs"),
            "import_jobs",
            ["import_job_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_items_closet_id_closets"),
            "closets",
            ["closet_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_items_valid_analysis_status"),
            "analysis_status IN ('processing', 'ready', 'failed')",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_items_valid_lifecycle_status"),
            "lifecycle_status IN ('active', 'archived', 'donated', 'sold', 'discarded')",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_items_valid_source_type"),
            "source_type IN ('camera', 'manual', 'shopping_screenshot', 'ootd')",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_items_valid_price"),
            "purchase_price IS NULL OR purchase_price >= 0",
        )
        batch_op.create_check_constraint(
            batch_op.f("ck_items_nonnegative_wear_count"),
            "wear_count >= 0",
        )

    if op.get_bind().dialect.name == "postgresql":
        for column_name in ("style_tags", "season_tags", "user_attributes"):
            op.alter_column(
                "items",
                column_name,
                existing_type=sa.JSON(),
                type_=postgresql.JSONB(),
                existing_nullable=False,
                postgresql_using=f"{column_name}::jsonb",
            )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("status", sa.String(length=20), server_default="active", nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_check_constraint(
            batch_op.f("ck_users_valid_status"),
            "status IN ('active', 'disabled', 'deleted')",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for column_name in ("style_tags", "season_tags", "user_attributes"):
            op.alter_column(
                "items",
                column_name,
                existing_type=postgresql.JSONB(),
                type_=sa.JSON(),
                existing_nullable=False,
                postgresql_using=f"{column_name}::json",
            )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_users_valid_status"), type_="check")
        batch_op.drop_column("deleted_at")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("status")

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_items_nonnegative_wear_count"), type_="check")
        batch_op.drop_constraint(batch_op.f("ck_items_valid_price"), type_="check")
        batch_op.drop_constraint(batch_op.f("ck_items_valid_source_type"), type_="check")
        batch_op.drop_constraint(batch_op.f("ck_items_valid_lifecycle_status"), type_="check")
        batch_op.drop_constraint(batch_op.f("ck_items_valid_analysis_status"), type_="check")
        batch_op.drop_constraint(batch_op.f("fk_items_closet_id_closets"), type_="foreignkey")
        batch_op.drop_constraint(
            batch_op.f("fk_items_import_job_id_import_jobs"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_items_closet_id_closets"), "closets", ["closet_id"], ["id"]
        )
        batch_op.drop_index(batch_op.f("ix_items_lifecycle_status"))
        batch_op.drop_index(batch_op.f("ix_items_import_job_id"))
        batch_op.drop_index("ix_items_closet_created")
        batch_op.drop_index("ix_items_closet_category_created")
        batch_op.drop_index(batch_op.f("ix_items_category"))
        batch_op.drop_index(batch_op.f("ix_items_analysis_status"))
        batch_op.drop_column("wear_count")
        batch_op.drop_column("last_worn_at")
        batch_op.drop_column("donated_at")
        batch_op.drop_column("acquired_at")
        batch_op.drop_column("currency")
        batch_op.drop_column("purchase_price")
        batch_op.drop_column("materials")
        batch_op.drop_column("colors")
        batch_op.drop_column("source_type")
        batch_op.drop_column("lifecycle_status")
        batch_op.drop_column("collection_name")
        batch_op.drop_column("brand")
        batch_op.drop_column("import_job_id")

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "analysis_status",
            new_column_name="status",
            existing_type=sa.String(length=30),
            existing_nullable=False,
        )

    with op.batch_alter_table("closets", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_closets_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_closets_user_id_users"), "users", ["user_id"], ["id"]
        )
        batch_op.drop_index(
            "uq_closets_default_per_user",
            postgresql_where=sa.text("is_default"),
            sqlite_where=sa.text("is_default = 1"),
        )
        batch_op.drop_column("archived_at")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("is_default")

    with op.batch_alter_table("auth_identities", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_auth_identities_valid_provider"), type_="check")
        batch_op.drop_constraint(batch_op.f("fk_auth_identities_user_id_users"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_auth_identities_user_id_users"), "users", ["user_id"], ["id"]
        )

    with op.batch_alter_table("item_analyses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_analyses_item_id"))
        batch_op.drop_index("ix_item_analyses_item_created")

    op.drop_table("item_analyses")
    op.drop_table("outfit_items")
    with op.batch_alter_table("item_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_images_sha256"))
        batch_op.drop_index(batch_op.f("ix_item_images_item_id"))

    op.drop_table("item_images")
    with op.batch_alter_table("analysis_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_analysis_jobs_status_queued")
        batch_op.drop_index(batch_op.f("ix_analysis_jobs_item_id"))

    op.drop_table("analysis_jobs")
    op.drop_table("outfit_reviews")
    with op.batch_alter_table("wear_events", schema=None) as batch_op:
        batch_op.drop_index("ix_wear_events_user_worn")
        batch_op.drop_index(batch_op.f("ix_wear_events_user_id"))
        batch_op.drop_index(batch_op.f("ix_wear_events_outfit_id"))

    op.drop_table("wear_events")
    with op.batch_alter_table("outfit_feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outfit_feedback_user_id"))
        batch_op.drop_index(batch_op.f("ix_outfit_feedback_outfit_id"))

    op.drop_table("outfit_feedback")
    with op.batch_alter_table("import_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_jobs_user_id"))
        batch_op.drop_index(batch_op.f("ix_import_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_import_jobs_closet_id"))

    op.drop_table("import_jobs")
    op.drop_table("user_profiles")
    op.drop_table("user_preferences")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_user_id"))

    op.drop_table("subscriptions")
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_tokens_user_id"))

    op.drop_table("refresh_tokens")
    with op.batch_alter_table("outfits", schema=None) as batch_op:
        batch_op.drop_index("ix_outfits_user_scheduled")
        batch_op.drop_index(batch_op.f("ix_outfits_user_id"))

    op.drop_table("outfits")
    # ### end Alembic commands ###
